'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Tournament

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''HF_SanctionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_SanctionID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_SkierID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_SkierID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_YearPkd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_YearPkd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_TournName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_TournName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_FormatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_FormatCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_SlalomRnds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_SlalomRnds As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_TrickRnds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_TrickRnds As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_JumpRnds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_JumpRnds As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_DisplayMetric control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_DisplayMetric As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_ROCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_ROCount As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_Errors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Errors As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDL_Format control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Format As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Btn_Back2TList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Back2TList As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_Home control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Home As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_Reports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Reports As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Lbl_ActiveEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_ActiveEvents As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DisplayText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DisplayText As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Officials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Officials As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Panel_Teams control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Teams As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_Teams control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Teams As Global.System.Web.UI.WebControls.Label
End Class
