'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TROandBR

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Panel_HF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_HF As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''HF_SanctionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_SanctionID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_SkierID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_SkierID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_Event control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_Event As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_AgeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_AgeGroup As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_RndPkd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_RndPkd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_YearPkd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_YearPkd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_TournName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_TournName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_FormatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_FormatCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_SlalomRnds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_SlalomRnds As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_TrickRnds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_TrickRnds As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_JumpRnds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_JumpRnds As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_UseNOPS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_UseNOPS As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_UseTeams control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_UseTeams As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_DisplayMetric control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_DisplayMetric As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_Errors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Errors As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel_Filters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Filters As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Panel_Filters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Filters As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDL_EventsPkd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_EventsPkd As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDL_DvPkd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_DvPkd As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDL_PkRnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_PkRnd As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Btn_2Tournament control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_2Tournament As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_2TList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_2TList As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_Home control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Home As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanelResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelResults As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Btn_UpdateDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_UpdateDisplay As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel_OnWater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_OnWater As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''OnWater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OnWater As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Panel_Row2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Row2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ColumnScores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ColumnScores As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
