'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TSkierListPro

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''HF_SanctionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_SanctionID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_SkierID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_SkierID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_Event control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_Event As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_AgeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_AgeGroup As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_YearPkd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_YearPkd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HF_TournName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF_TournName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_Errors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Errors As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Btn_2Tournament control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_2Tournament As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_2TList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_2TList As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_Home control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Home As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''InsertHere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InsertHere As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
